apiVersion: apps/v1
kind: Deployment
metadata:
  name: safe-check-deploy-{{ .Values.environment }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: safe-check-deploy-{{ .Values.environment }}
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: safe-check-deploy-{{ .Values.environment }}
  template:
    metadata:
      labels:
        app: safe-check-deploy-{{ .Values.environment }}
        environment: {{ .Values.environment }}
    spec:
      nodeSelector:
{{ toYaml .Values.deployment.nodeSelector | indent 8 }}
      containers:
        - name: safe-check-container-{{ .Values.environment }}
          image: "{{ .Values.deployment.image.repository }}/{{ .Values.environment }}:latest"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
          startupProbe:
            httpGet:
              path: {{ .Values.deployment.probes.startup.path }}
              port: {{ .Values.deployment.probes.startup.port }}
            failureThreshold: {{ .Values.deployment.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.deployment.probes.startup.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.probes.liveness.path }}
              port: {{ .Values.deployment.probes.liveness.port }}
            initialDelaySeconds: {{ .Values.deployment.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.deployment.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.probes.readiness.path }}
              port: {{ .Values.deployment.probes.readiness.port }}
            initialDelaySeconds: {{ .Values.deployment.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.deployment.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.deployment.probes.readiness.failureThreshold }}
          volumeMounts:
            - name: safe-check-data-{{ .Values.environment }}
              mountPath: /var/lib/check_{{ .Values.environment }}
          envFrom:
            - secretRef:
                name: {{ printf "safe-check-%s-secret" .Values.environment }}
          env:
            - name: SPRING_ACTIVE_PROFILES
              value: "{{ .Values.environment }}"
      volumes:
        - name: safe-check-data-{{ .Values.environment }}
          persistentVolumeClaim:
            claimName: {{ printf "safe-check-data-%s" .Values.environment }}